version: '3'

services:
  db:
    container_name: db_container
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_DATABASE: BLOCKs
      #MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: ifrea1201
      #MYSQL_ALLOW_EMPTY_PASSWORD: ifrea1201
      #MYSQL_RANDOM_ROOT_PASSWORD: ifrea1201
      MYSQL_ALLOW_EMPTY_PASSWORD: ‘yes’
    volumes:
      - db-vol:/var/lib/mysql
    ports:
      - 3306:3306

  web:
    container_name: app_container
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    working_dir: /code
    ports:
      - 8000:8000
    volumes:
      - /Users/kimotoshoho/Desktop/BLOCKs:/code
    depends_on:
      - db

volumes :
  db-vol:
